sonar.projectKey=pharmacy-online
sonar.projectName=Online Pharmacy and Medicine Deliveryy
sonar.projectVersion=1.0
sonar.sources=CatalogService/src/main,pharmacy-admin/src/main,pharmacy-auth/src/main,pharmacy-config-server/src/main,pharmacy-eureka/src/main,pharmacy-gateway/src/main,pharmacy-order/src/main
sonar.tests=CatalogService/src/test,pharmacy-admin/src/test,pharmacy-auth/src/test,pharmacy-config-server/src/test,pharmacy-eureka/src/test,pharmacy-gateway/src/test,pharmacy-order/src/test
sonar.java.binaries=CatalogService/target/classes,pharmacy-admin/target/classes,pharmacy-auth/target/classes,pharmacy-config-server/target/classes,pharmacy-eureka/target/classes,pharmacy-gateway/target/classes,pharmacy-order/target/classes
sonar.host.url=http://localhost:9000
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=**/target/surefire-reports
sonar.exclusions=**/target/**,**/.metadata/**,**/uploads/**,**/reports/**,**/temp/**,**/tools/**
